apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.6.2  
    helm:
      values: |
        alloy:
          rbac:
            create: true
          controller:
            type: daemonset
          configMap:
            create: true
            content: |
              discovery.kubernetes "all_pods" {
                role = "pod"
              }

              discovery.relabel "openldap_filter" {
                targets = discovery.kubernetes.all_pods.targets

                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app"]
                  regex         = "openldap"
                  action        = "keep"
                }

                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app"]
                  target_label  = "app"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  target_label  = "pod"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  target_label  = "container"
                }
              }

              loki.source.kubernetes "pod_logs" {
                targets    = discovery.relabel.openldap_filter.output
                forward_to = [loki.write.local.receiver]
              }

              loki.write "local" {
                endpoint {
                  url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
                }
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }