loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  auth_enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
promtail:
  enabled: false
alloy:
  enabled: true
gateway:
  enabled: false
grafana:
  enabled: false 
  sidecar:
    datasources:
      enabled: false