loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 1d 

promtail:
  enabled: true
  config:
    loki_address: http://loki-stack:3100/loki/api/v1/push
