apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: curity-db-ha
  namespace: curity-dev
spec:
  instances: 3

  
  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: curity
      owner: curityuser
      secret:
        name: db-user-creds
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: curity-db-init-sql
            key: postgres-create_database.sql