apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: curity-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: test-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: CURITY_URL
          value: "https://dev.curity.local"
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: curity-dev
spec:
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-app-ingress
  namespace: curity-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: test-app.curity.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-app-service
            port:
              number: 80