---
- name: Rol de Nginx Ingress Controller uit via Argo CD
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: nginx-ingress
        namespace: argocd
      spec:
        project: default
        source:
          chart: ingress-nginx
          repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.1.1
          helm:
            values: |
              controller:
                kind: DaemonSet
                hostNetwork: true
                dnsPolicy: ClusterFirstWithHostNet
                service:
                  type: ClusterIP
                publishService:
                  enabled: false
        destination:
          server: https://kubernetes.default.svc
          namespace: ingress-nginx
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true

- name: Rol de CloudNativePG Operator uit via Argo CD
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: cloudnative-pg-operator
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://cloudnative-pg.github.io/charts
          targetRevision: '0.27.1'
          chart: cloudnative-pg
        destination:
          server: https://kubernetes.default.svc
          namespace: cloudnative-pg
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
            - replace=true

- name: "Installeer de Monitoring Stack via ArgoCD"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: kube-prometheus-stack
        namespace: argocd
      spec:
        project: default
        source:
          chart: kube-prometheus-stack
          repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision: 82.4.3
          helm:
            values: |
              grafana:
                adminPassword: "{{ grafana_admin_password }}"
                grafana.ini:
                  server:
                    domain: {{ grafana_link }}
                    root_url: https://{{ grafana_link }}
                    serve_from_sub_path: false
                service:
                  type: ClusterIP
                sidecar:
                  dashboards:
                    enabled: true
                    label: grafana_dashboard
                    labelValue: "1"
                    searchNamespace: ALL
                dashboardProviders:
                  dashboardproviders.yaml:
                    apiVersion: 1
                    providers:
                    - name: 'default'
                      orgId: 1
                      folder: ''
                      type: file
                      disableDeletion: false
                      editable: true
                      options:
                        path: /var/lib/grafana/dashboards/default
                dashboards:
                  default:
                    curity-authenticators:
                      gnetId: 14421
                      revision: 1
                      datasource: Prometheus
              prometheus:
                prometheusSpec:
                  retention: 10d
                  serviceMonitorSelectorNilUsesHelmValues: false
                  serviceMonitorNamespaceSelector: {}
                  serviceMonitorSelector: {}
                  podMonitorSelectorNilUsesHelmValues: false
                  podMonitorSelector: {}
                  podMonitorNamespaceSelector: {}
        destination:
          server: "https://kubernetes.default.svc"
          namespace: monitoring
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true

- name: "Wacht tot ServiceMonitor CRD beschikbaar is"
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  register: crd_status
  until: crd_status.resources | length > 0
  retries: 10
  delay: 15

- name: "Maak ServiceMonitor voor Curity"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: curity-monitor
        namespace: monitoring
        labels:
          release: kube-prometheus-stack
      spec:
        namespaceSelector:
          matchNames:
            - curity-{{ env }}
        selector:
          matchLabels:
            app.kubernetes.io/name: idsvr
            app.kubernetes.io/instance: curity-dev-stack
            role: curity-dev-stack-idsvr-runtime
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 30s

- name: "ConfigMap: Database Init SQL"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: curity-db-init-sql
        namespace: "curity-{{ env }}"
      data:
        postgres-create_database.sql: "{{ lookup('file', local_secret_path + 'postgres-create_database.sql') }}"


- name: "Apply Master Argo App voor {{ env  }}"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('template', 'templates/master-app.yaml.j2') }}"