---
- name: Activeer Nginx Ingress Controller via GitOps
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/s152628/Stage-project-curity/main/apps/nginx-ingress.yaml', split_lines=False) | from_yaml }}"

- name: Activeer CloudNativePG Operator via Argo CD
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/s152628/Stage-project-curity/main/apps/cloudnativepg.yaml', split_lines=False) | from_yaml }}"


- name: "Activeer Monitoring via GitOps"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/s152628/Stage-project-curity/main/apps/monitoring/monitoring.yaml', split_lines=False) | from_yaml }}"

- name: "Activeer Loki via GitOps"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/s152628/Stage-project-curity/main/apps/monitoring/loki-application.yaml', split_lines=False) | from_yaml }}"

- name: "Activeer Grafana Alloy via GitOps"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/s152628/Stage-project-curity/main/apps/monitoring/grafana-alloy.yaml', split_lines=False) | from_yaml }}"

- name: "Activeer google-hash-service via GitOps voor omgeving {{ env }}"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/s152628/Stage-project-curity/main/apps/google-hash-service/google-hash-service-' + env + '.yaml', split_lines=False) | from_yaml_all | list }}"
    
- name: "Wacht tot ServiceMonitor CRD beschikbaar is"
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  register: crd_status
  until: crd_status.resources | length > 0
  retries: 10
  delay: 15

- name: "Maak ServiceMonitor voor Curity"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: curity-monitor-{{ env }}
        namespace: monitoring
        labels:
          release: kube-prometheus-stack
      spec:
        namespaceSelector:
          matchNames:
            - curity-{{ env }}
        selector:
          matchLabels:
            app.kubernetes.io/name: idsvr
            app.kubernetes.io/instance: curity-{{ env }}-stack
            role: curity-{{ env }}-stack-idsvr-runtime
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 30s

- name: "ConfigMap: Database Init SQL"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: curity-db-init-sql
        namespace: "curity-{{ env }}"
      data:
        postgres-create_database.sql: "{{ lookup('file', local_secret_path + 'postgres-create_database.sql') }}"


- name: "Apply Master Argo App voor {{ env  }}"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('template', 'templates/master-app.yaml.j2') }}"