- name: Wacht tot ArgoCD de wijziging oppakt en de Deployment aanmaakt (max 5 min)
  ansible.builtin.shell: |
    kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get statefulset openldap -n curity-{{ env }}
  register: sts_check
  until: sts_check.rc == 0
  retries: 30 
  delay: 10
  changed_when: false

- name: Wacht tot de OpenLDAP database is opgestart en klaar is voor data
  ansible.builtin.shell: |
    kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml wait \
      --namespace curity-{{ env }} \
      --for=condition=Ready pod/openldap-0 \
      --timeout=300s
  changed_when: false
- name: Lees users.json in als variabele
  ansible.builtin.include_vars:
    file: users.json
    name: user_data

- name: Vertaal JSON naar LDIF en injecteer direct in OpenLDAP voor {{ env }}
  ansible.builtin.shell: |
    kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml exec -i -n curity-{{ env }} openldap-0 -- ldapadd -x -D "cn=admin,dc=camazotz,dc=me" -w "{{ openldap_admin_password }}" -H ldap://localhost << 'EOF'
    dn: ou=people,dc=camazotz,dc=me
    objectClass: organizationalUnit
    ou: people

    {% for user in user_data.users %}
    dn: uid={{ user.uid }},ou=people,dc=camazotz,dc=me
    objectClass: inetOrgPerson
    objectClass: top
    uid: {{ user.uid }}
    cn: {{ user.uid }}
    sn: {{ user.lastName }}
    givenName: {{ user.firstName }}
    mail: {{ user.email }}
    userPassword: {{ user.password }}
    telephoneNumber: {{ user.telephoneNumber }}

    {% endfor %}
    EOF
  register: ldap_result
  failed_when: ldap_result.rc not in [0, 68]
  changed_when: ldap_result.rc == 0