- name: Activeer tailscale bridge via GitOps
  kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition: "{{ lookup('url', 'https://raw.githubusercontent.com/s152628/Stage-project-curity/main/apps/tailscale-bridge-app.yaml', split_lines=False) | from_yaml }}"