apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-tunnel
  namespace: curity-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok-tunnel
  template:
    metadata:
      labels:
        app: ngrok-tunnel
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:latest
        args:
        - "http"
        - "https://curity-dev-idsvr-runtime-svc:8443"
        - "--host-header=dev.curity.local"
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: ngrok-secret
              key: AUTHTOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: ngrok-tunnel-svc
  namespace: curity-dev
spec:
  selector:
    app: ngrok-tunnel
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040