apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  namespace: curity-dev
spec:
  serviceName: "openldap-headless"
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        command:
          - /bin/sh
          - -c
          - |
            # Bereken de unieke Server ID (1, 2, 3) op basis van de Pod Index
            INDEX=$(hostname | rev | cut -d'-' -f1 | rev)
            export LDAP_SERVER_ID=$((INDEX + 1))
            echo "Bootstrapping LDAP with ServerID: $LDAP_SERVER_ID"
            exec /container/tool/run --copy-service
        env:
        - name: LDAP_LOG_LEVEL
          value: "256"
        - name: LDAP_ORGANISATION
          value: "Camazotz"
        - name: LDAP_DOMAIN
          value: "camazotz.me"
        - name: LDAP_ADMIN_PASSWORD_FILE
          value: "/vault/secrets/admin-pass"
        - name: LDAP_CONFIG_PASSWORD_FILE 
          value: "/vault/secrets/admin-pass"

        - name: LDAP_REPLICATION
          value: "true"
        
        - name: LDAP_REPLICATION_HOSTS
          value: "ldap://openldap-0.openldap-headless.curity-dev.svc.cluster.local ldap://openldap-1.openldap-headless.curity-dev.svc.cluster.local ldap://openldap-2.openldap-headless.curity-dev.svc.cluster.local"
        
        - name: LDAP_REPLICATION_DB_SYNCPROV
          value: "binddn=\"cn=admin,dc=camazotz,dc=me\" bindmethod=simple credentials=$(cat /vault/secrets/admin-pass) searchbase=\"dc=camazotz,dc=me\" type=refreshAndPersist retry=\"5 5 300 5\" timeout=1"
        - name: LDAP_REPLICATION_CONFIG_SYNCPROV
          value: "binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=$(cat /vault/secrets/admin-pass) searchbase=\"cn=config\" type=refreshAndPersist retry=\"5 5 300 5\" timeout=1"

        - name: LDAP_WAIT_FOR_HOSTS
          value: "false"
        - name: LDAP_TLS
          value: "false"

        volumeMounts:
        - name: ldap-storage
          mountPath: /var/lib/ldap
          subPath: data
        - name: ldap-storage
          mountPath: /etc/ldap/slapd.d
          subPath: config

  volumeClaimTemplates:
  - metadata:
      name: ldap-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
  namespace: curity-dev
spec:
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-headless
  namespace: curity-dev
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openldap-sa
  namespace: curity-dev