apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  namespace: curity-dev
spec:
  serviceName: "openldap-headless"
  replicas: 3
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "openldap-role-dev"
        vault.hashicorp.com/agent-inject-secret-admin-pass: "secret/data/dev/openldap/vars"
        vault.hashicorp.com/agent-inject-template-admin-pass: |
          {{- with secret "secret/data/dev/openldap/vars" -}}
          {{ .Data.data.ADMIN_PASSWORD }}
          {{- end -}}
    spec:
      serviceAccountName: openldap-sa
      securityContext:
        fsGroup: 911
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        securityContext: 
          runAsUser: 0
          runAsGroup: 0
        command: ["/container/tool/run"]
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 636
          name: ldaps
        env:
        - name: LDAP_LOG_LEVEL
          value: "256"
        - name: LDAP_ORGANISATION
          value: "Camazotz"
        - name: LDAP_DOMAIN
          value: "camazotz.me"
        - name: LDAP_ADMIN_PASSWORD_FILE
          value: "/vault/secrets/admin-pass"
        - name: "LDAP_WAIT_FOR_HOSTS"
          value: "true"
        - name: LDAP_REPLICATION
          value: "true"
        - name: LDAP_REPLICATION_HOSTS
          value: "#PYTHON2BASH:['ldap://openldap-0.openldap-headless','ldap://openldap-1.openldap-headless','ldap://openldap-2.openldap-headless']"
        - name: LDAP_REPLICATION_DB_SYNC_URL
          value: "ldap://openldap-0.openldap-headless"
        - name: LDAP_REPLICATION_CONFIG_SYNC_URL
          value: "ldap://openldap-0.openldap-headless"
        volumeMounts:
        - name: ldap-storage
          mountPath: /var/lib/ldap
          subPath: data
        - name: ldap-storage
          mountPath: /etc/ldap/slapd.d
          subPath: config

  volumeClaimTemplates:
  - metadata:
      name: ldap-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
  namespace: curity-dev
spec:
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      targetPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-headless
  namespace: curity-dev
spec:
  clusterIP: None
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openldap-sa
  namespace: curity-dev