replicaCount: 3
curity:
  config:
    license: true
    cluster:
      enabled: true
    uiEnabled: true
    configuration: 
      - secretRef:
          name: curity-config-secret
          items:
            - key: configuration.xml
              path: configuration.xml
    environmentVariableSecrets:
     - curity-cluster-secret
     - curity-vars
  admin:
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 3
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 1Gi
  runtime:
    env:
      - name: LOGGING_LEVEL
        value: "DEBUG"
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 3
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 1Gi
    service:
      type: ClusterIP
      port: 8443
      labels:
        app: curity-runtime
        release: kube-prometheus-stack
      additionalPorts:
        - name: metrics
          port: 4466
          targetPort: 4466
    
ingress:
  enabled: true
  admin:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      kubernetes.io/ingress.class: "nginx"
    host: auth-admin-dev.camazotz.me
    paths:
      - /
  runtime:
    enabled: true
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: role
                  operator: In
                  values:
                    - curity-runtime
            topologyKey: "kubernetes.io/hostname"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "route"
      nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    host: auth-dev.camazotz.me
    paths:
      - / 