apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://cloudnative-pg.github.io/charts'
      targetRevision: '0.27.1'
      chart: cloudnative-pg

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudnative-pg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - replace=true