apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curity-full-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://cloudnative-pg.github.io/charts'
      chart: cloundnative-pg
      targetRevision: '0.27.1'
      
    - repoURL: 'https://github.com/s152628/Stage-project-curity.git'
      targetRevision: HEAD
      path: 'confs/dev'
    
    - repoURL: 'https://curityio.github.io/idsvr-helm/'
      targetRevision: '0.13.18'
      chart: idsvr
      helm:
        valueFiles:
          - '$values/confs/dev/values.yaml'
  
  sourceNames:
    - operator
    - infra
    - values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: curity-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true