apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-bridge
  namespace: curity-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-bridge
  template:
    metadata:
      labels:
        app: tailscale-bridge
    spec:
      serviceAccountName: tailscale-sa
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth 
              key: TS_AUTHKEY     
        - name: TS_EXTRA_ARGS
          value: "--hostname=curity-k8s-tunnel"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: ts-state
          mountPath: /var/lib/tailscale
      - name: bridge
        image: alpine/socat
        command: ["sh", "-c", "socat TCP-LISTEN:8443,fork,reuseaddr TCP:nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:443 & socat TCP-LISTEN:8081,fork,reuseaddr TCP:argocd-server.argocd.svc.cluster.local:443 & socat TCP-LISTEN:8082,fork,reuseaddr TCP:nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:443"]
      volumes:
      - name: ts-state
        emptyDir: {}