apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/s152628/Stage-project-curity.git'
    targetRevision: HEAD
    path: apps/testapp/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: curity-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true